---
title: "Crime in Northwest Philadelphia"
runtime: shiny
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(dplyr)
library(KernSmooth)
#library(raster)
#library(RColorBrewer)

load("data/points.RData")
load("data/points_year.RData")
load("data/bb.RData")

# points_year <- points
# points_year$year <- as.POSIXlt(points_year$DISPATCH_DATE)$year + 1900
# points_year$TYPE <- as.character(points_year$TYPE)

```

Crime Occurences
================

Select date range and crime type {.sidebar}
-------------------------------------------

```{r}

#Make some inputs
dateRangeInput("dates", "Date range:", start = "2016-01-01", end = "2016-07-24",
               min = "2006-01-01", max = "2016-07-24", startview = "year", separator = "to")

checkboxGroupInput("type", "Crime type:", choices = c("Homicides", "Assaults", "Sexual assaults"),
                   selected = "Homicides")

#Filter points to be displayed based on the inputs
points_filter <- reactive({
    filter(points, DISPATCH_DATE >= as.POSIXct(format(input$dates[1]), format = "%Y-%m-%d")
           & DISPATCH_DATE <=  as.POSIXct(format(input$dates[2]), format = "%Y-%m-%d")
           & TYPE %in% input$type)
  })

#Make a color pallete for crime types
type_pal <- reactive({
    colorFactor(topo.colors(3), points$TYPE)
  })

```

This map shows the location of different types of violent crime in northwest
Philadelphia from the start of 2006 to July 24, 2016 (the date the data were
accessed). This visualization is incomplete as entries in the database without
an easily accessible latitude and longitude (of which there are many) aren't
shown on the map.

In the original data, the crimes were further subdivided. I've ommited these
categories for the sake of clarity and interpretability of the map. The assault
category was divided into assaults with a firearm, assaults without a firearm,
and all other assaults. Homicides were categorized as either criminal,
negligent, or justifiable. The sexual assault categories were the vaguest. I
chose to include crimes categorized as rape and a catch-all other category of
noncommercial sex offenses. It's very possible that some important nuance has
been lost in these categorizations.

The data were collected from
[OpenDataPhilly](https://www.opendataphilly.org/dataset/crime-incidents) and no
ownership is claimed. This work is licensed under the [MIT
License](https://opensource.org/licenses/MIT).

Map
-------

```{r}
#Make a map
output$map <- renderLeaflet({
    leaflet(points) %>%
      addProviderTiles("Stamen.TonerLite") %>%
      fitBounds(~min(LON), ~min(LAT), ~max(LON), ~max(LAT))
  })

#Add stuff to it
observe({
    pal <- type_pal()
    leafletProxy("map", data = points_filter()) %>%
      clearMarkers() %>%
      addCircleMarkers(~LON, ~LAT, color = ~pal(TYPE), radius = 3, opacity = 1) %>%
      clearControls() %>%
      addLegend("bottomright", pal, ~TYPE, title = "Crime type")
  })

#This makes the map take up the whole vertical space available
tags$style(type = "text/css", "#map {height: calc(100vh - 80px) !important;}")
leafletOutput("map")
```

Crime Density
=============

Select year {.sidebar}
----------------------

```{r}
#Make inputs
sliderInput("year_heat", "Year:", min = 2006, max = 2016, value = 2016, step = 1,
            ticks = FALSE, round = TRUE,
            sep = "") #check out animate once everything is working...
radioButtons("type_heat", "Crime type:",
             choices = c("Homicides", "Assaults", "Sexual assaults"), 
             selected = "Homicides")
checkboxInput("display_points", "Display points", value = FALSE)

#Filter points again
points_filter_heat <- reactive({
  shiny::validate(need(input$year_heat, label = "year")) #For some reason it won't work without this
  points_year %>% 
   filter(year == input$year_heat
            & points_year$TYPE %in% input$type_heat)
  })

#Reactive kernel density estimate
kde <- reactive({
  bkde2D(cbind(points_filter_heat()$LON, points_filter_heat()$LAT), 
         bandwidth = c(dpik(points_filter_heat()$LON), dpik(points_filter_heat()$LAT)))
})

#The total area under the kde for normalization. Not sure if this actually works
#right tho....
# norm <- reactive({
#   int <- 0
#   for(i in 1:(nrow(kde()$fhat)-1)){
#     for(j in 1:(ncol(kde()$fhat)-1)){
#       int <- int + kde()$fhat[i,j]*(kde()$x1[j+1]-kde()$x1[j])*(kde()$x2[i+1]-kde()$x2[1])
#     }
#   }
#   int
# })


#Create contour lines of the density
contours <- reactive({
  contourLines(kde()$x1, kde()$x2, kde()$fhat)
})

#Also a raster heatmap
# heat_raster <- reactive({
#   raster(list(x = kde()$x1, y = kde()$x2, z = kde()$fhat))
# })

#A color palette for the contours. The mess of a domain unpacks the list
#structure of the contour lines, matches the entries that correspond to the
#equiprobable levels, and then makes a vector containing each level once
contour_pal <- reactive({
  colorFactor(palette = "Reds",
              domain = unique(unlist(contours())[grepl("level", attr(unlist(contours()), "names"))]))
})

```

This map uses the same data as the map of crime occurences, but applies a 
technique called kernel density estimation to the data points. The goal is to 
use the historical data to estimate how likely it is that a crime will occur 
close to a given point on the map. The contour lines represent paths of equal 
probability density over the map. Think of them like the contours that indicate 
elevation on a topographical map, but now in areas of high "elevation," a crime 
of the selected type is more likely to have occured than in an area of lower 
"elevation." Take note, however, that the numbers on the legend are **not** 
actual probabilities. They are only present to provide a sense of scale for the 
contours. They should only be used for comparisons within the context of the map
view currently on display.

Maybe the most useful way to intepret this presentation is to recognize that the
areas of high probability density (or "elevation," in the topographical 
metaphor) are areas in which crimes appear to be clustered. Perhaps some 
underlying pattern can be found in the ways in which these areas shift from year
to year or what underlying factors are correlated with an area of high crime
density.

Map
-------

```{r}
#Make the map
output$map_heat <- renderLeaflet({
    leaflet(points_year) %>%
    addProviderTiles("Stamen.TonerLite") %>%
    fitBounds(~min(LON), ~min(LAT), ~max(LON), ~max(LAT))
  })

#Add the raster heat map
# observe({
#   leafletProxy("map_heat") %>%
#     clearImages() %>%
#     addRasterImage(heat_raster(), colors = pal())
#   })


#Add the contours
observe({
  #define temporary values for convenience, again with the mess from the palette
  pal_temp <- contour_pal()
  #norm_temp <- norm()
  values_temp <- unique(unlist(contours())[grepl("level", attr(unlist(contours()), "names"))])
  
  #Clear off everything old
  leafletProxy("map_heat") %>%
    clearShapes() %>% 
    clearMarkers()
  
    if(input$display_points){
    leafletProxy("map_heat", data = points_filter_heat()) %>% 
      clearMarkers() %>% 
      addCircleMarkers(~LON, ~LAT, color = "coral", radius = 3, opacity = .7)
  }

  #Add the right number of contours
  for(i in 1:length(contours())){
    leafletProxy("map_heat") %>% 
      addPolylines(contours()[[i]]$x, contours()[[i]]$y,
                   color = pal_temp(contours()[[i]]$level), weight = 4, opacity = .6)
  }
  
  #Add the legend
  leafletProxy("map_heat") %>% 
    clearControls() %>% 
    addLegend("bottomleft", pal = pal_temp, values = values_temp,
              labFormat = labelFormat(digits = 3, transform = function(x) x))
              #Normalize only on legend output
  

  })


#Make it big
tags$style(type = "text/css", "#map_heat {height: calc(100vh - 80px) !important;}")
leafletOutput("map_heat")
```

